site_name: Documentation
site_url: https://formcloudapp.github.io/fc_doc/
theme:
  name: material
  logo: assets/logo-dark.svg
  font:
    text: 'Roboto'
    code: 'Red Hat Mono'
  features:
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: rgb(34, 40, 160)
      accent: light green
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: rgb(34, 40, 160)
      accent: light green
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/quang-nguyen-formcloud/
    - icon: material/youtube
      link: https://www.youtube.com/@FormCloud

copyright: Copyright © 2025 Formcloud

nav:
  - Getting Started: index.md
  - Page:
      - Introduction: Page/overview.md
      - Create a new Page: Page/example.md
  - Widget:
      - Introduction: Widget/overview.md
      - Create and embed a new Widget: Widget/example.md
      - Passing options into the Widget: Widget/example2.md
  - Components:
    - DataTable: 
      - Introduction: Components/Datatable/overview.md
      - Default Configuration: Components/Datatable/default.md
      - Create a new DataTable: Components/Datatable/example.md
    - Form:
      - Introduction: Components/Form/overview.md
      - Create a Record Producer form: Components/Form/example.md
      - Section:
        - Introduction: Components/Form/Section/overview.md
      - Question:
        - Introduction: Components/Form/Section/Question/overview.md
        - Configurations: Components/Form/Section/Question/configuration.md
        - Text: Components/Form/Section/Question/text.md
  - API Reference:
    - Repository:
      - Overview: API/overview.md
      - FCRepository: API/FCRepository.md
      - FCTaskRepository: API/FCTaskRepository.md
    - Utility:
      - FCPersonaUtility: API/FCPersonaUtility.md
      - FCLoggerUtility: API/FCLoggerUtility.md

plugins:
  - glightbox
  - search

extra_css:
  - stylesheets/style.css